#include "nuitrack_bridge/types/gesture_data.h"


// This header is generated by CXX from the gesture.rs file,
// giving us access to the Rust-defined types in C++.
#include "nuitrack-rs/src/nuitrack_bridge/types/gesture.rs.h"

namespace nuitrack_bridge::gesture_data {

    // --- GestureData Implementations ---

    uint64_t getGestureDataTimestamp(const GestureData& data) {
        return data.getTimestamp();
    }

    int32_t getGestureDataNumGestures(const GestureData& data) {
        return static_cast<int32_t>(data.getNumGestures());
    }

    rust::Slice<const Gesture> getGestureDataGestures(const GestureData& data) {
        const auto& vec = data.getGestures();
        return rust::Slice<const Gesture>{
            reinterpret_cast<const Gesture*>(vec.data()),
            vec.size()
        };
    }

    // --- UserStateData Implementations ---

    uint64_t getUserStateDataTimestamp(const UserStateData& data) {
        return data.getTimestamp();
    }

    int32_t getUserStateDataNumUserStates(const UserStateData& data) {
        return static_cast<int32_t>(data.getNumUserStates());
    }

    rust::Slice<const UserState> getUserStateDataUserStates(const UserStateData& data) {
        const auto& vec = data.getUserStates();
        return rust::Slice<const UserState>{
            reinterpret_cast<const UserState*>(vec.data()),
            vec.size()
        };
    }

    // --- UserGesturesStateData Implementations ---

    uint64_t getUserGesturesStateDataTimestamp(const UserGesturesStateData& data) {
        return data.getTimestamp();
    }

    int32_t getUserGesturesStateDataNumUsers(const UserGesturesStateData& data) {
        return static_cast<int32_t>(data.getNumUsers());
    }

    std::unique_ptr<std::vector<UserGesturesState>> getUserGesturesStateDataUserGesturesStates(const UserGesturesStateData& data) {
        // This returns a std::vector by value, so we wrap it in a unique_ptr for Rust.
        return std::make_unique<std::vector<UserGesturesState>>(data.getUserGesturesStates());
    }

}