#pragma once

#include "rust/cxx.h"
#include <memory>
#include <vector>


#include "nuitrack/types/Gesture.h"

namespace nuitrack_bridge::gesture {
    // Alias for the original Nuitrack type
    using UserGesturesState = tdv::nuitrack::UserGesturesState;
    // Alias for the Rust-defined type that will be generated by CXX
    struct GestureState;
    enum class UserStateType : int32_t;

    int32_t getUserID(const UserGesturesState& state);
    UserStateType getUserState(const UserGesturesState& state);
    rust::Slice<const GestureState> getGestures(const UserGesturesState& state);
}