#pragma once

// This header includes the C++ definition of the Vector3 struct
// that is generated by CXX from the corresponding Rust definition.
#include "nuitrack-rs/src/nuitrack_bridge/types/vector3.rs.h"